"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";

type ProfileRow = { id:string; registrationId:string; fullName:string; gender:string; dateOfBirth:string; caste:string; city:string; district:string; mobile:string; email:string; status:"pending"|"approved"|"rejected"; photoKey:string|null; details:Record<string,string>; createdAt:string };
type Share = { id:string; recipientName:string; recipientContact:string; channel:"whatsapp"|"email"|"manual"; status:"sent"|"viewed"|"interested"|"declined"|"follow_up"; profileConsent:string; contactConsent:string; notes:string; createdAt:string };
const privateKeys = new Set(["mobile","email","address","pincode"]);

export default function AdminDashboard({ user, signOutPath }: { user:{name:string;email:string}; signOutPath:string }) {
  const [rows,setRows]=useState<ProfileRow[]>([]), [status,setStatus]=useState("all"), [query,setQuery]=useState(""), [selected,setSelected]=useState<ProfileRow|null>(null);
  const [loading,setLoading]=useState(true), [message,setMessage]=useState(""), [shareMode,setShareMode]=useState(false), [shares,setShares]=useState<Share[]>([]);
  const [recipientName,setRecipientName]=useState(""), [recipientContact,setRecipientContact]=useState(""), [channel,setChannel]=useState<"whatsapp"|"email"|"manual">("whatsapp"), [notes,setNotes]=useState(""), [consent,setConsent]=useState(false), [shareError,setShareError]=useState("");

  const load=useCallback(async()=>{setLoading(true);const response=await fetch(`/api/admin/profiles?status=${status}&q=${encodeURIComponent(query)}`);const data=await response.json() as {profiles?:ProfileRow[];error?:string};setRows(data.profiles||[]);setMessage(data.error||"");setLoading(false)},[status,query]);
  useEffect(()=>{const timer=setTimeout(load,250);return()=>clearTimeout(timer)},[load]);
  const loadShares=useCallback(async(id:string)=>{const response=await fetch(`/api/admin/shares?profileId=${id}`);const data=await response.json() as {shares?:Share[]};setShares(data.shares||[])},[]);
  const counts=useMemo(()=>({all:rows.length,pending:rows.filter(r=>r.status==="pending").length,approved:rows.filter(r=>r.status==="approved").length,rejected:rows.filter(r=>r.status==="rejected").length}),[rows]);
  async function changeStatus(row:ProfileRow,next:ProfileRow["status"]){await fetch("/api/admin/profiles",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:row.id,status:next})});setSelected(current=>current?{...current,status:next}:null);setMessage(`Profile ${next}.`);await load()}
  function beginShare(row:ProfileRow){setSelected(row);setShareMode(true);setShareError("");loadShares(row.id)}
  async function recordShare(event:FormEvent){event.preventDefault();if(!selected)return;setShareError("");const response=await fetch("/api/admin/shares",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({profileId:selected.id,recipientName,recipientContact,channel,notes,profileConsent:consent})});const data=await response.json() as {error?:string};if(!response.ok){setShareError(data.error||"Unable to record share.");return}await loadShares(selected.id);const text=`Vanakkam, please find the privacy-safe matrimony profile of ${selected.fullName} (${selected.registrationId}). Home address and private contact details have been removed.`;if(channel==="whatsapp")window.open(`https://wa.me/${recipientContact.replace(/\D/g,"")}?text=${encodeURIComponent(text)}`,"_blank","noopener,noreferrer");if(channel==="email")window.location.href=`mailto:${recipientContact}?subject=${encodeURIComponent(`Matrimony Profile – ${selected.fullName}`)}&body=${encodeURIComponent(`${text}\n\nPlease attach the saved PDF before sending.`)}`;setRecipientName("");setRecipientContact("");setNotes("");setConsent(false);setMessage("Sharing recorded. Attach the PDF to the prepared message.")}
  async function updateShare(item:Share,next:Share["status"]){await fetch("/api/admin/shares",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:item.id,status:next})});if(selected)await loadShares(selected.id)}
  function closeModal(){setSelected(null);setShareMode(false)}

  return <main className="admin-page">
    <aside className="admin-sidebar"><a className="brand admin-brand" href="/"><span className="brand-mark">M</span><span>MilanMitra</span></a><nav><a className="active" href="/admin">◫ Profiles</a><a href="/register">＋ New registration</a><a href="/">⌂ Website</a></nav><div className="admin-user"><span>{user.name.charAt(0).toUpperCase()}</span><div><strong>{user.name}</strong><small>{user.email}</small></div><a href={signOutPath}>Sign out</a></div></aside>
    <section className="admin-content"><header><div><span className="kicker">ADMIN CONSOLE</span><h1>Profile management</h1><p>Review, approve and securely share registered profiles.</p></div><a className="button" href="/register">＋ Add profile</a></header>
      <div className="admin-stats"><article><span>Total profiles</span><strong>{counts.all}</strong></article><article><span>Awaiting review</span><strong>{counts.pending}</strong></article><article><span>Approved</span><strong>{counts.approved}</strong></article><article><span>Rejected</span><strong>{counts.rejected}</strong></article></div>
      <div className="admin-toolbar"><label>⌕<input placeholder="Search name, ID, phone or city" value={query} onChange={e=>setQuery(e.target.value)}/></label><select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All statuses</option><option value="pending">Pending</option><option value="approved">Approved</option><option value="rejected">Rejected</option></select></div>{message&&<p className="admin-message">{message}</p>}
      <div className="admin-table"><div className="admin-row admin-table-head"><span>Profile</span><span>Contact</span><span>Location</span><span>Status</span><span></span></div>{loading?<div className="admin-empty">Loading profiles…</div>:rows.length?rows.map(row=><button className="admin-row" key={row.id} onClick={()=>setSelected(row)}><span><strong>{row.fullName}</strong><small>{row.registrationId} · {row.gender}</small></span><span><strong>{row.mobile}</strong><small>{row.email||"No email"}</small></span><span><strong>{row.city||"—"}</strong><small>{row.district||row.caste||"—"}</small></span><span><i className={`status-dot ${row.status}`}/>{row.status}</span><span>View →</span></button>):<div className="admin-empty"><strong>No profiles found</strong><span>New registrations will appear here automatically.</span></div>}</div>
    </section>
    {selected&&<div className="admin-modal-backdrop no-print" onClick={closeModal}><article className={`admin-modal ${shareMode?"share-modal":""}`} onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={closeModal}>×</button>{shareMode?<SharePanel profile={selected} shares={shares} recipientName={recipientName} setRecipientName={setRecipientName} recipientContact={recipientContact} setRecipientContact={setRecipientContact} channel={channel} setChannel={setChannel} notes={notes} setNotes={setNotes} consent={consent} setConsent={setConsent} error={shareError} submit={recordShare} updateShare={updateShare} back={()=>setShareMode(false)}/>:<><span className="kicker">{selected.registrationId}</span><h2>{selected.fullName}</h2><div className="modal-status"><i className={`status-dot ${selected.status}`}/>{selected.status}</div><div className="modal-data">{Object.entries(selected.details).filter(([,v])=>v).map(([key,value])=><div key={key}><span>{key.replace(/([A-Z])/g," $1")}</span><strong>{value}</strong></div>)}</div><div className="modal-privacy">🔒 Phone, email and address are visible only in this admin view and remain excluded from the shared PDF.</div><div className="modal-actions"><button className="ghost-button reject" onClick={()=>changeStatus(selected,"rejected")}>Reject</button><button className="ghost-button" onClick={()=>changeStatus(selected,"pending")}>Mark pending</button>{selected.status==="approved"?<button className="button" onClick={()=>beginShare(selected)}>Share profile →</button>:<button className="button" onClick={()=>changeStatus(selected,"approved")}>✓ Approve profile</button>}</div></>}</article></div>}
    {shareMode&&selected&&<PrintableProfile profile={selected}/>} 
  </main>;
}

function SharePanel(p:{profile:ProfileRow;shares:Share[];recipientName:string;setRecipientName:(v:string)=>void;recipientContact:string;setRecipientContact:(v:string)=>void;channel:"whatsapp"|"email"|"manual";setChannel:(v:"whatsapp"|"email"|"manual")=>void;notes:string;setNotes:(v:string)=>void;consent:boolean;setConsent:(v:boolean)=>void;error:string;submit:(e:FormEvent)=>void;updateShare:(s:Share,v:Share["status"])=>void;back:()=>void}){return <><button className="share-back" onClick={p.back}>← Profile details</button><span className="kicker">PRIVACY-SAFE SHARING</span><h2>{p.profile.fullName}</h2><div className="share-summary"><span>✓ Approved</span><strong>{p.profile.registrationId}</strong><button className="ghost-button" onClick={()=>window.print()}>Download / Print PDF</button></div><div className="modal-privacy">🔒 The PDF automatically omits phone number, email, full address and PIN code.</div><form className="share-form" onSubmit={p.submit}><h3>Record a new share</h3><div className="form-grid"><label className="form-field"><span>Recipient name</span><input required value={p.recipientName} onChange={e=>p.setRecipientName(e.target.value)}/></label><label className="form-field"><span>WhatsApp number or email</span><input value={p.recipientContact} onChange={e=>p.setRecipientContact(e.target.value)}/></label><label className="form-field"><span>Sharing method</span><select value={p.channel} onChange={e=>p.setChannel(e.target.value as typeof p.channel)}><option value="whatsapp">WhatsApp</option><option value="email">Email</option><option value="manual">Manual / In person</option></select></label><label className="form-field"><span>Note</span><input value={p.notes} onChange={e=>p.setNotes(e.target.value)} placeholder="Optional follow-up note"/></label></div><label className="consent-check"><input type="checkbox" checked={p.consent} onChange={e=>p.setConsent(e.target.checked)}/><span>I confirm the profile owner has consented to this share. Private contact details will remain hidden.</span></label>{p.error&&<p className="form-error">{p.error}</p>}<button className="button share-submit" disabled={!p.consent}>Record & prepare {p.channel}</button></form><section className="share-history"><h3>Sharing history</h3>{p.shares.length?p.shares.map(item=><article key={item.id}><div><strong>{item.recipientName}</strong><span>{item.channel} · {new Date(item.createdAt).toLocaleDateString("en-IN")}</span></div><select value={item.status} onChange={e=>p.updateShare(item,e.target.value as Share["status"])}><option value="sent">Sent</option><option value="viewed">Viewed</option><option value="interested">Interested</option><option value="declined">Declined</option><option value="follow_up">Follow-up</option></select></article>):<p>No sharing records yet.</p>}</section></>}

function PrintableProfile({profile}:{profile:ProfileRow}){const data=Object.entries(profile.details).filter(([k,v])=>v&&!privateKeys.has(k));return <article className="admin-print-profile"><header><div><span>MATRIMONY PROFILE</span><h1>{profile.fullName}</h1><p>{profile.registrationId}</p></div><strong>M</strong></header><section><h2>Profile details</h2><div>{data.map(([key,value])=><p key={key}><span>{key.replace(/([A-Z])/g," $1")}</span><strong>{value}</strong></p>)}</div></section><aside><strong>Privacy protected</strong><span>Home address, phone number, email and PIN code are intentionally omitted.</span></aside><footer><strong>MilanMitra</strong><span>Thoughtful connections. Beautiful beginnings.</span><span>{profile.registrationId}</span></footer></article>}
